[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Feature-Policy = "geolocation=none; microphone=none; camera=none"
    Strict-Transport-Security = "max-age=31536000"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "script-src 'https://s.adroll.com/j/roundtrip.js https://a.quora.com/qevents.js https://connect.facebook.net/en_US/fbevents.js https://platform.twitter.com/widgets.js https://www.googletagmanager.com/gtm.js https://www.google-analytics.com/analytics.js 'unsafe-inline' 'self'"
