import React from 'react';
import {Col, Grid, Row} from 'react-styled-flexboxgrid';
import Link from 'next/link';

import { PolicyWrapper, List, TextLink, AnchorTitle } from './styled';

export const Policy = () => {
    return (
        <Grid className="container">
            <Row>
                <Col xs={12} md={12}>
                    <PolicyWrapper>
                        <h1>
                            Privacy Policy
                        </h1>
                        <List>
                            <li>
                                <Link href="#shortTermPolicy"><a>Short form</a></Link>
                            </li>
                            <li>
                                <Link href="#fullFormPolicy"><a>Full form</a></Link>
                            </li>
                            <li>
                                <Link href="https://www.lykke.com/media/documents/Privacy_Policy_23.05.2018.pdf"><a>PDF Version</a></Link>
                            </li>
                        </List>
                        <p>23 MAY 2018</p>
                        <p>This is the Privacy Policy of Lykke Corp UK Ltd, a company incorporated under the laws of the United Kingdom with registration number 10093552 and registered address 86-90 Paul Street, London, United Kingdom, EC2A 4NE (hereinafter called «Lykke,» «we,» or «us»). Lykke is a 100% subsidiary of Lykke Corp, a company incorporated under the laws of Switzerland with registration number CHE-345.258.499 and registered address 2 Baarerstrasse, 6300 Zug, Switzerland. This Privacy Policy is applying also to Lykke Corp and to other entities of the Lykke Group</p>
                        <p>Lykke understands that your privacy is important. Lykke is strongly committed to protecting your privacy and the personal information that you may provide to Lykke as you access and use the materials on Lykke.com, Lykkex.com (the «Sites»), our iOS and Android mobile apps (the «Apps»), recipients of our emails, or when you otherwise interact with us, including the subscription pages of the Sites.</p>
                        <p>In addition, information that you submit to Lykke in response to an email request for information or other outreach from Lykke, or through the Lykke employment application processes, will also be treated in accordance with this Privacy Policy.</p>
                        <p>In this written Privacy Policy, Lykke describes the use of your personal data by Lykke and the scope and breadth of our commitment to privacy. Lykke may, in its discretion, amend this Privacy Policy from time to time. Any material changes to our policy will be reflected on this page, so that you remain informed about the information we collect and how we use it. By exploring and using the Sites and Apps, and by submitting information to Lykke, you agree to Lykke use of such information as described herein.</p>
                        <p>The Sites and Apps may contain links to external Sites, which are not governed by this privacy policy, and Lykke does not take responsibility for the privacy practices of any third-party Sites to which we link. We encourage you to review the privacy policies of such Sites before you submit information there.</p>
                        <AnchorTitle id="shortTermPolicy">Short form privacy policy</AnchorTitle>
                        <h3>Your data privacy with Lykke</h3>
                        <p>At Lykke we care about your privacy and want you to be confident in the way we use your personal information and other data. This page provides a summary for you. If you’d like to read our privacy policy and other terms and conditions in full then select <Link href="/terms-and-regulation"><TextLink href="/terms-and-regulation">here</TextLink></Link> </p>
                        <p>Our data privacy policy applies to all of the products and services we provide you as a customer and user of our site and apps.</p>
                        <p>The information we collect about you helps us provide the best service possible to you. It also helps us keep your information safe and comply with laws and regulations.</p>
                        <h3>About us</h3>
                        <p>We are Lykke Corp, a Swiss based company but we do have other subsidiaries and affiliates. If you want further information on our any of our companies or wish to get in contact with us you can do <Link href="/contacts"><TextLink href="/contacts">here</TextLink></Link>.</p>
                        <h3>What we do with your data</h3>
                        <p>We use the personal information you give us in various ways but primarily to allow us to provide you with the products and services you’d like to use as well as offer our support services. We also use it to help protect you and our services from crime, such as fraud or money laundering. We may share your information with our other group companies and selected third parties but always make sure it remains protected. We don’t sell or make available your data to any third parties for marketing, advertising or related purposes.</p>
                        <h3>What sort of information do we ask you for</h3>
                        <p>Depending on what services you want to use or products you want to buy or trade in we will ask you for various information. This could be your email address or contact number so we can communicate with you or be some form of proof of identity such as an I.D. card, driving license or passport and a ‘selfie’. To help us get to know you as a customer and comply with applicable laws and regulations - such as anti money laundering, fraud or sanctions - we may require a proof of address and when trading or investing, a proof of banking details and funds.</p>
                        <h3>What information are we entitled to</h3>
                        <p>We need and are permitted to have your information for three reasons - either because you have agreed to give it to us, or to be able to provide our products and services to you, or because we are legally required to obtain it. In each case we will only ask for, store and use information that we reasonably require and we will only hold on to if for as long as we need to or that the law requires us to do.</p>
                        <h3>Where do we store your information</h3>
                        <p>All our data and your information is held in secure servers. We do use a number of different operating systems. In each case the data we store, how we store it and third party applications we use are subject to strict security measures and legal obligations.</p>
                        <h3>How we keep your information safe</h3>
                        <p>We use a number of technical and procedural measures to ensure the safety of your data. These include encrypting data, only storing and transferring it where we know it is safe and restricting access to who can see or use the data.</p>
                        <h3>Who can access or see my information</h3>
                        <p>Only those people within our organisation that need to see it in order to help us provide our products and services to you. This will include our customer service and support staff as well as specific ‘Know Your Customer’ or ‘KYC’ and compliance staff who need to ensure we follow applicable laws and regulations. We may pass your information to selected third parties for specific purposes such as carrying our KYC and identity checks.</p>
                        <h3>What rights do I have to my information</h3>
                        <p>You have various rights in your information such as the right to ask us what information we hold about you, ask us to correct or delete information about you or to restrict our use of it. You also have the right to request us to export or transfer data to other companies. And you have the right to complain about our use of your data and submit a complaint to the relevant data protection authority.</p>
                        <h3>Who do I contact to find our more or make a complaint</h3>
                        <p>If you have any questions, comments or complaints regarding how we collect, use and store information about you, Lykke Corp. has Data Protection Officer to help you. If you need assistance, please send an e-mail to <TextLink href="mailto:dpo@lykke.com">dpo@lykke.com</TextLink>.</p>
                        <AnchorTitle id="fullFormPolicy">Full form privacy policy</AnchorTitle>
                        <h3>Information that we collect, and how we use it</h3>
                        <p>Lykke collects information from our users when they create their account for the Sites or the Apps, when they request copies of publications, seek additional information regarding our services, or register for conferences and other Lykke events. Some of the forms for Lykke registration, enrollment, account setup, and other purposes may ask users to give us contact information, unique personal identifiers, financial information, subject areas of interest, and/or demographic information. We may use these data to tailor the visitor’s experience at our Sites and Apps or, if applicable, to assess the candidacy of an individual and qualifications for employment with Lykke.</p>
                        <p>You agree that Lykke may use any personal information that you provide, such as your name, address, email address, phone number, subject areas of interest, etc., to inform you about updates to the service and to notify you about other products and services offered by Lykke that may be of interest to you. We will not sell, share, or rent or otherwise make available any of that information to other parties, except that we may disclose the information to third parties who perform services on our behalf and have a need to access the information in connection with the performance of those services. In addition, you agree that Lykke may disclose your contact information in response to inquiries by bona-fide rights owners in connection with allegations of infringement of copyright or other proprietary rights arising from information that you have posted on the Sites or otherwise provided to Lykke. Individuals that subscribe to email newsletters are given the opportunity to opt out of promotions, news, and information at the time of signup. Lykke also provides users the opportunity to opt out of receiving communications from us at the points where we request information. You may also feel free to contact us as indicated below if you wish to opt out of communications received from Lykke at a later point.</p>
                        <h3>Email addresses</h3>
                        <p>We may collect the email addresses at the point of subscription of users who wish to receive email notification of publications and press releases in identified subject areas of interest, and of those who send us email messages or express interest regarding our services or employment opportunities, or register for conferences and other Lykke-sponsored events. We will not, however, share any email addresses with any third party or send unsolicited email to any of the addresses we collect, except in very limited circumstances as set forth in this policy.</p>
                        <p>If you opted in to receive information about our product, updates, and offers, we will use your name and email address to send this information to you. If you no longer wish to receive these communications, you can unsubscribe by following the instructions contained in the emails you receive or on our Sites. Please note that we may send you transactional and relationship messages, even if you have unsubscribed from our marketing communications. For instance, if our service is going to be temporarily suspended for maintenance, we might send you an email to update you.</p>
                        <h3>Cookie policy</h3>
                        <p>This cookie policy lets you know what cookies are and how Lykke uses them. It also lets you know how you can disable them if you do not wish them to be used. Please take the time to read this policy and if you continue to use any of Lykke’s sites you will be agreeing to our use of them in line with this policy.</p>
                        <h4>What is a cookie?</h4>
                        <p>Cookies are small files that contain data and are stored on your computer, iPad or mobile device. They contain information that lets the website you are accessing remember you on the site and let us know what your preferences when using the site.</p>
                        <h4>Why do we use them?</h4>
                        <p>Like all websites and customer facing service providers nowadays we use them to make your use of the site easier and offer a better user experience. For example, it allows you to logon without having to re-enter your password or tell us your preferences each time. It also lets us understand what our customers are interested in and make improvements to our site and the services we offer.</p>
                        <h4>Types of  cookie</h4>
                        <p>We use ‘Session Cookies’, ‘Persistent Cookies’ and ‘Third Party Cookies’ on our sites.</p>
                        <p>Session Cookies are temporary files on your computer that allow a website to identify your actions and choices during a browsing session. They expire when you leave the site and close your web browser.</p>
                        <p>Persistent Cookies are stored on your computer and remain there after you close your browser or switch off your computer. They are then used next time you log on to our sites to help us identify you and your preferences. They do not contain any information that would allow us to identify you to another user or another user.</p>
                        <p>Third Party Cookies let us connect with another provider, such as Google’ to provide links to functionality or analytics. We use Google Analytics which uses cookies to analyse our use of the site. The information generated by the cookie about your use of the site (including your IP address) is stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google’s behalf. Google will not associate your IP address with any other data held by Google. If you do not wish to allow the use of Third Party Cookies you can erase or block them.</p>
                        <h4>What if I don’t want to allow cookies or want to block them?</h4>
                        <p>With most Internet browsers, you can erase cookies from your computer hard drive, block all cookies, or receive a warning before a cookie is stored on your computer. Please refer to your browser instructions or a help screen to learn more about these functions and how to use them. If you get stuck you can also call our helpdesk. Please note that if you do choose to block or disable cookies then certain sections or functionalities of our sites may be inaccessible to you as will some of the functionality that requires the use of cookies.</p>
                        <h3>International transfer of information</h3>
                        <p>Because Lykke is a global organization, information collected on the Sites or Apps or through other means may be transferred from time to time among the Lykke offices or personnel, or to third parties located throughout the world, including offices located outside the European Economic Area, and the Sites may be viewed and hosted anywhere in the world, including countries that may not have laws regulating the use and transfer of personally identifiable data. Lykke has in place contractual safeguards to ensure that foreign Lykke entities as well as third-party contractors adhere to the applicable laws and regulations as well as this Privacy Policy. By using the Sites, submitting information through the Sites, or submitting information to Lykke through other means, you voluntarily consent to such international transfer and hosting of such information.</p>
                        <h3>Security processes</h3>
                        <p>Lykke has in place technological and operational security processes designed to protect personally identifiable information from loss, misuse, alteration, or destruction. Only authorized employees and contractors will have access to any data provided by you, and that access is limited by need. Each employee or contractor having access to any personally identifiable information is obligated to maintain its confidentiality. Although we take steps that are generally accepted as industry standard to protect your personally identifiable information, Lykke cannot guarantee that your personally identifiable information will not become accessible to unauthorized persons.</p>
                        <h3>Links to other websites</h3>
                        <p>Our Sites may include links to other websites or online services whose privacy practices may differ from those of Lykke. If you submit information to any of those websites or online services, your information is governed by their privacy statements. We encourage you to read carefully the privacy statement of any websites you visit. Lykke is not responsible for the privacy practices or the content of any non-Lykke websites to which we link from the Sites or Apps.</p>
                        <h3>Compliance with law</h3>
                        <p>Lykke complies with all applicable privacy laws and regulations. Lykke may be compelled to surrender personal user or customer information to legal authorities without express user consent if presented with a court subpoena or similar legal or administrative order, or as required or permitted by the laws, rules, and regulations of any nation, state, or other applicable jurisdiction. Also, in the event of a violation of the terms and conditions of use of the Sites and the Apps or a violation of any restrictions on use of materials provided in or through the Sites, we may disclose personal user information to our affected business partners or legal authorities.</p>
                        <h3>Change and/or delete information</h3>
                        <p>You may access, correct, update, and/or delete, as the case may be, any personally identifiable information that you submit to Lykke through the Sites or the Apps or through other means. To do so, please either follow instructions on the page of the Sites on which you have provided such information or subscribed or registered or contact us.</p>
                        <h3>Children</h3>
                        <p>Lykke understands the importance of protecting children’s privacy, particularly in their online interactions. The Sites and the Apps are not designed for and do not intentionally target or solicit to persons 18 years of age and younger.</p>
                        <h3>Use of Lykke websites</h3>
                        <p>Your access to and use of the Sites and the Apps are subject to certain terms and conditions, which are summarized in our <Link href="/terms-of-use"><TextLink href="/terms-of-use">Terms and Conditions of Use</TextLink></Link>.</p>
                        <h3>Contact us</h3>
                        <p>If you have any questions about this Privacy Policy or the collection and use of information by Lykke, please contact our Data Protection Officer: <TextLink href="mailto:dpo@lykke.com">dpo@lykke.com</TextLink>. <br/>
                            For general queries and support, you can contact us here: <TextLink href="mailto:support@lykke.com">support@lykke.com</TextLink> .</p>
                    </PolicyWrapper>
                </Col>
            </Row>
        </Grid>
    )
}